### ISSUE TITLE
Time wrong and Homepage not updateing

### ISSUE THREAD

**Issue by FreeSoftwareServers** [deweysasser/docker-xymon-client#2]
My xymon server is half working. The main page doesn't update, but if I click on a process being monitored that page has updated correct results. As well, the time is wrong on my setup but I passed the TZ environment variable.

Suggestions?

**Comment by deweysasser** [comment]
@FreeSoftwareServers Sorry for the long delay here.  I'm getting back to maintaining these projects.  I'm going to close this issue assuming that you've solved it by now, but if that's not true, please let me know.
